[application]
name = "Thoth"
default_platform = "desktop"

[web.app]
title = "Thoth"

[web.watcher]

[web.build]
public_dir = "public"

[web.resources]
style = ["assets/tailwind.css"]

[desktop.app]
title = ""
window_decorations = false
